### PR TITLE
fix: guard Import latest commit for read-only repositories only

### LINKED ISSUE #8727: bug: CoreRepository type git repo unable to sync from last commit
### Component

API Server / GraphQL

### Infrahub version

1.8.1

### Current Behavior

Recently upgraded to community edition 1.8.1 after upgrade I cannot run the action "import latest commit" on a git repository that is of type CoreRepository. I get the following infrahub-server errors:
```
infrahub-server-1  | 2026-03-29T19:33:58.642100Z [critical ] Unhandled exception occurred in resolvers [infrahub.graphql] app=infrahub.api request_id=cfa2e163970049989c3a47b690e3123f worker=a569ca4f-8f8e-4a8f-b596-827a9063f309
infrahub-server-1  | Traceback (most recent call last):
infrahub-server-1  |   File "/.venv/lib/python3.13/site-packages/graphql/execution/execute.py", line 530, in await_result
infrahub-server-1  |     return_type, field_nodes, info, path, await result
infrahub-server-1  |                                           ^^^^^^^^^^^^
infrahub-server-1  |   File "/source/backend/infrahub/graphql/mutations/repository.py", line 258, in mutate
infrahub-server-1  |     ref=str(repo.ref.value),
infrahub-server-1  |             ^^^^^^^^
infrahub-server-1  | AttributeError: 'Node' object has no attribute 'ref'
infrahub-server-1  | 2026-03-29T19:35:10.205893Z [info     ] menu_request                   [infrahub] app=infrahub.api branch=menu_object_test request_id=091c5b21fa9b4f6ca9d7a62141a56bce worker=edc0ad78-4a8e-4117-b82e-8b115f9473b5
```

### Expected Behavior

Running the "import latest commit" action should work with no errors.

### Steps to Reproduce

1. Load clean docker compose deployment of Infrahub `1.8.1`
2. Add git repo of type CoreRepository and confirm initial in-sync state and git artifacts are loaded.
3. Attempt to run "import latest commit" action from the webUI

### Additional Information

Looking a little deeper in the traceback it appears my repository is getting directed in to a `ReadOnlyRepositoryImportLastCommit` type of object which would understandably not find repo that is type CoreRepository. 

Graphql state of git repositories where this error is triggered from:

```
{
  "data": {
    "CoreRepository": {
      "edges": [
        {
          "node": {
            "hfid": [
              "infrahub-forgejo"
            ]
          }
        }
      ]
    },
    "CoreReadOnlyRepository": {
      "edges": []
    }
  }
}
```

### PR DESCRIPTION
**Pull request by BeArchiTek**
## Summary
Fixes #8727 

- "Import latest commit" button was shown for **all** repository types but called `ReadOnlyRepositoryImportLastCommit`, which accesses `.ref` — an attribute only present on `CoreReadOnlyRepository`
- Clicking it on a `CoreRepository` caused `'Node' object has no attribute 'ref'`
- Regression introduced in #8183 when the frontend switched from `InfrahubRepositoryProcess` to `InfrahubReadOnlyRepositoryImportLastCommit` without adding a kind guard

## Changes
- **Frontend**: Guard "Import latest commit" button with `isReadOnlyRepository`
- **Backend**: Add kind validation in `ReadOnlyRepositoryImportLastCommit.mutate()` before accessing `.ref`
- **Tests**: Backend test for rejection case + updated frontend tests

## Test plan
- [ ] Verify "Import latest commit" button is **not shown** on `CoreRepository` detail page
- [ ] Verify "Import latest commit" button **is shown** on `CoreReadOnlyRepository` detail page
- [ ] Verify clicking "Import latest commit" on a read-only repo works as before
- [ ] Run `npx vitest run src/entities/repository/ui/repository-menu-section.test.tsx`
- [ ] Run backend component test `test_import_last_commit_rejects_non_read_only_repository`

### CODE REVIEW

File: backend/infrahub/graphql/mutations/repository.py [hunk 1]
```diff
@@ -250,6 +250,12 @@ async def mutate(
             branch=branch,
         )
 
+        if repo.get_kind() != InfrahubKind.READONLYREPOSITORY:
+            raise ValueError(
```
Comment (ogenstad) [inline backend/infrahub/graphql/mutations/repository.py]: We'd want to raise our internal ValidationError here instead of a base error from Python.

**Review by pa-lem — APPROVED** [review]

**Comment by ogenstad** [comment]
Will you also add a newsfragment to indicate that the bug was fixed?

**Review by ogenstad — APPROVED** [review]
