### PR TITLE
Merge release-1.10 into develop

### PR DESCRIPTION
**Pull request by polmichel**
Supersedes #9589, which was blocked on a frontend build/lint failure after merging release-1.10.

## Summary

Merges `release-1.10` into `develop`.

## Conflicts resolved

Clean auto-merge — no textual conflicts. One semantic incompatibility surfaced in CI on #9589:

- `frontend/app/src/entities/path-traversal/ui/dependencies-mode/dependencies-mode-form.tsx` — the path-traversal feature (from release-1.10) imported `Checkbox` from `@/shared/components/inputs/checkbox` using the native-input props API. On `develop` that component was moved into the `@infrahub/ui` package and switched to the react-aria API. Repointed the import to `@infrahub/ui` and updated the usage to `isSelected` / `onChange(boolean)`. (`ce93f9134`)

This single change resolves all the #9589 CI failures, which shared one root cause (the unresolved import broke the frontend build):
- `frontend-lint` (knip unresolved import)
- `backend-docker-integration` (vite/rolldown failed to resolve the import during `pnpm build`)
- `E2E-testing-playwright` (image build failed, so E2E never ran)
- `backend-tests-unit (3.12)` (cancelled as matrix fail-fast collateral)

## Conflicts raised for review

None.

## Validation

- `biome` clean and `knip` passes on the changed file.
- `pnpm build` succeeds (10,611 modules transformed) — the import resolves.
- `pnpm codegen` produces no drift in frontend generated types.
- Not run locally: backend unit/integration tests and backend generated-file validation (require the full backend stack).

🤖 Generated with [Claude Code](https://claude.com/claude-code)

---
## Summary by cubic
Merges `release-1.10` into `develop` and fixes a frontend build break by switching the path-traversal form to the `@infrahub/ui` `Checkbox` (react-aria API).

- **New Features**
  - Faster path traversal with a new renderer/executor; adds a “shortest paths only” option (default) and per-depth execution.
  - GraphQL adds `included_kinds` and applies default exclusions (e.g. IP namespace kinds); UI exposes the shortest-paths toggle.

- **Bug Fixes**
  - Rejects `at` query times earlier than branch creation at REST/GraphQL with clear 422 errors.
  - SSO default group is assigned only on a user’s first login; docs updated.
  - Git sync uses the repository’s Git default branch for initial import and pinned commit; adds tests.
  - Upgrades `gitpython` to `3.1.50` (security fix).
  - Proposed change actions surface backend error messages; “Sync with Git” checkbox is no longer marked required.

<sup>Written for commit ce93f91349d45362d38bfd116fac9d2c440f368f. Summary will update on new commits.</sup>

<a href="https://cubic.dev/pr/opsmill/infrahub/pull/9614?utm_source=github" target="_blank" rel="noopener noreferrer" data-no-image-dialog="true"><picture><source media="(prefers-color-scheme: dark)" srcset="https://www.cubic.dev/buttons/review-in-cubic-dark.svg"><source media="(prefers-color-scheme: light)" srcset="https://www.cubic.dev/buttons/review-in-cubic-light.svg">Review in cubic</picture></a>

### CODE REVIEW

**Review by bilalabbad — APPROVED** [review]

File: backend/infrahub/api/dependencies.py [hunk 1]
```diff
@@ -82,7 +83,11 @@ async def get_branch_params(
     branch = await registry.get_branch(db=db, branch=branch_name)
     request.state.branch_name = branch.name
 
-    return BranchParams(branch=branch, at=Timestamp(at))
+    at_ts = Timestamp(at)
+    if at is not None:
+        BranchQueryTimeValidator(registry=registry).validate(branch=branch, at=at_ts)
```
[the remark this answers is not in the document]
Comment (polmichel) [reply backend/infrahub/api/dependencies.py:88]: This exact gating is already inside `validate` method

File: backend/infrahub/graph_traversal/executor.py [hunk 2]
```diff
@@ -0,0 +1,50 @@
...
+    its rows internally.
+    """
+
+    def __init__(self, *, db: InfrahubDatabase, branch: Branch, renderer: GraphTraversalCypherRenderer) -> None:
+        self._db = db
+        self._branch = branch
+        self._renderer = renderer
+
+    async def run(self, *, plan: Plan, source_id: str, max_paths: int, at: Timestamp | None = None) -> list[PathData]:
+        at = at if at is not None else Timestamp()
```
[the remark this answers is not in the document]
Comment (polmichel) [reply backend/infrahub/graph_traversal/executor.py:32]: Nitpick comment but seems to be objectively better. Will be tackled in this PR https://github.com/opsmill/infrahub/pull/9623
